import { Listing } from '../../interfaces/listing';

export const getListingsMockResponse: Listing[] = [
    {
        _id: '5d91c8c875fa8927668f8dca',
        name: 'Diego',
        price: '100.00',
        description: 'blah blah blah blah blah blah blah blah blah blah blah blah',
        expertiseArea: 'PERSONAL_COACH',
        pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
        postCode: 'NW13LR',
        createdByExpert: {
            approvedStatus: 'APPROVED',
            _id: '5d91c66f75fa8927668f8dc9',
            email: 'diegoromero.audio@gmail.com',
            name: 'Diego',
            description: 'blah blah blah',
            pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
            createdTimeStamp: '2019-09-30T09:10:07.531Z',
        },
        createdTimeStamp: '2019-09-30T09:20:08.446Z',
        __v: 0,
    },
    {
        _id: '5d91c8c875fa8927668f8dca',
        name: 'Diego',
        price: '100.00',
        description: 'blah blah blah blah blah blah blah blah blah blah blah blah',
        expertiseArea: 'PERSONAL_COACH',
        pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
        postCode: 'NW13LR',
        createdByExpert: {
            approvedStatus: 'APPROVED',
            _id: '5d91c66f75fa8927668f8dc9',
            email: 'diegoromero.audio@gmail.com',
            name: 'Diego',
            description: 'blah blah blah',
            pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
            createdTimeStamp: '2019-09-30T09:10:07.531Z',
        },
        createdTimeStamp: '2019-09-30T09:20:08.446Z',
        __v: 0,
    },
    {
        _id: '5d91c8c875fa8927668f8dca',
        name: 'Diego',
        price: '100.00',
        description: 'blah blah blah blah blah blah blah blah blah blah blah blah',
        expertiseArea: 'PERSONAL_COACH',
        pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
        postCode: 'NW13LR',
        createdByExpert: {
            approvedStatus: 'APPROVED',
            _id: '5d91c66f75fa8927668f8dc9',
            email: 'diegoromero.audio@gmail.com',
            name: 'Diego',
            description: 'blah blah blah',
            pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
            createdTimeStamp: '2019-09-30T09:10:07.531Z',
        },
        createdTimeStamp: '2019-09-30T09:20:08.446Z',
        __v: 0,
    },
    {
        _id: '5d91c8c875fa8927668f8dca',
        name: 'Diego',
        price: '100.00',
        description: 'blah blah blah blah blah blah blah blah blah blah blah blah',
        expertiseArea: 'PERSONAL_COACH',
        pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
        postCode: 'NW13LR',
        createdByExpert: {
            approvedStatus: 'APPROVED',
            _id: '5d91c66f75fa8927668f8dc9',
            email: 'diegoromero.audio@gmail.com',
            name: 'Diego',
            description: 'blah blah blah',
            pictureUrl: 'https://fitmind-dev.s3.eu-west-2.amazonaws.com/mock-images/daniel_photo.png',
            createdTimeStamp: '2019-09-30T09:10:07.531Z',
        },
        createdTimeStamp: '2019-09-30T09:20:08.446Z',
        __v: 0,
    },
];
